# Generated by Django 4.2.11 on 2024-04-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='retailer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='briefing.retailer'),
            preserve_default=False,
        ),
    ]
