# Generated by Django 4.2.11 on 2024-04-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0002_remove_retailer_vendor_vendor_retailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='briefing',
            old_name='available_date',
            new_name='available',
        ),
    ]
