# Generated by Django 4.2.11 on 2024-04-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('briefing', '0004_rename_available_briefing_availabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='briefing.retailer'),
        ),
    ]
